### ISSUE TITLE
Bound the Image Movement in Clippath area

### ISSUE THREAD

**Issue by ravneetdhamija007** [fabricjs/api-discussion#11]
I have used Clipping Now I Want to Restrict the movement of of Image after it cross the rectangle right corner or bottom of rectangle in fabric Js

I have Bound the image from top and bottom but right and bottom is not working as expected need your help

https://stackoverflow.com/questions/63740245/i-have-used-clipping-now-i-want-to-restrict-the-movement-of-of-image-after-it-cr

https://jsfiddle.net/mg73n0eq/154/#&togetherjs=Qh6LnTRHFq

**Comment by asturur** [comment]
Hi @ravneetdhamija007 this forum would be for library api and is should be used to discuss coming changes or to suggest some.
Not for help request.
